%% fetch SMS data
SMS_CA_data = sln_results.DatasetSMSCA * ...
    aka.Dataset * ...
    proj(sln_animal.Animal,'source_id->animal_source','*') * ...
    sln_animal.GenotypeString * sln_cell.Cell * ...
    sln_symphony.UserParamCellLabeled * ...
    sln_symphony.UserParamDatasetDrugPresent * ...
    proj(sln_cell.AssignType.current,'entry_time->cell_assign_entry','user_name->cell_assign_user','*') & ...
    (proj(aka.BlockParams('SpotsMultiSize'), 'mean_level') & 'mean_level=0' & 'stim_time_ms=1000') & ...
    'cell_class="RGC"' & ...
    'dob IS NOT NULL' & ...
    'drug_present IS NULL';

%filter datasets we don't want
SMS_CA_RGCs = SMS_CA_data & ...
    'dataset_name NOT LIKE "%Laser%"' & ...
    'dataset_name NOT LIKE "%10k%"' & ...
    'dataset_name NOT LIKE "%meanON%"' & ...
    'dataset_name NOT LIKE "%mean035%"' & ...
    'dataset_name NOT LIKE "%mean0.2%"' & ...
    'dataset_name NOT LIKE "%mean_wContras%"' & ...
    'dataset_name NOT LIKE "%HighGlucose%"' & ...
    'dataset_name NOT LIKE "%Wash%"' & ...
    'dataset_name NOT LIKE "%functionalImaging%"' & ...
    'dataset_name NOT LIKE "%fromMean%"' & ...
    'dataset_name NOT LIKE "%darkspot%"' & ...
    'dataset_name NOT LIKE "%MFA%"' & ...
    'dataset_name NOT LIKE "%Z1_8Hz%"' & ...
    'dataset_name NOT LIKE "%NDF7%"' & ...
    'dataset_name NOT LIKE "%11Cis%"' & ...
    'strain_name!="WT_bead_injected"' & ...
    'strain_name!="NF1-KO"' & ...
    'strain_name!="Tusc5-eGFP"' & ...
    'cell_type!="unknown"' & ...
    'strain_name!="TRPV4_cKO_bead_injected"';

%% get MP data
MP_data = sln_results.DatasetMultiPulsevaryCurrentFeatureExtract * ...
    aka.Dataset * ...
    proj(sln_animal.Animal,'source_id->animal_source','*') * ...
    sln_animal.GenotypeString * sln_cell.Cell * ...
    sln_symphony.UserParamCellLabeled * ...
    sln_symphony.UserParamDatasetDrugPresent * ...
    proj(sln_cell.AssignType.current,'entry_time->cell_assign_entry','user_name->cell_assign_user','*') & ...
    'cell_class="RGC"' & ...
    'cell_type!="unknown"' & ...
    'dob IS NOT NULL' & ...
    'drug_present IS NULL';

MP_data_RGCs = MP_data & ...
    'dataset_name NOT LIKE "%Loss_access%"' & ...
    'dataset_name NOT LIKE "%meh_access%"' & ...
    'dataset_name NOT LIKE "%insulin%"' & ...
    'dataset_name NOT LIKE "%10s%"' & ...
    'dataset_name NOT LIKE "%TTX%"' & ...
    'dataset_name NOT LIKE "%2s%"' & ...
    'dataset_name NOT LIKE "%4s%"' & ...
    'dataset_name NOT LIKE "%SynBlock%"' & ...
    'dataset_name NOT LIKE "%wash%"' & ...
    'strain_name!="WT_bead_injected"' & ...
    'strain_name!="NF1-KO"' & ...
    'strain_name!="Tusc5-eGFP"' & ...'
    'strain_name!="TRPV4_cKO_bead_injected"';

%% Get matching ones and extract them
ids = unique(fetchn(MP_data_RGCs,'cell_unid'));

z=1;
data = struct;
for i=1:length(ids)
    i
    q_MP = MP_data_RGCs & sprintf('cell_unid=%d',ids(i));
    if q_MP.count == 1
        q_SMS = SMS_CA_RGCs & sprintf('cell_unid=%d',ids(i));
        if q_SMS.count == 1
            data(z).current_injections = fetch(q_MP,'*');
            epochs = sln_symphony.DatasetEpoch * ...
                sln_symphony.ExperimentChannel * ...
                sln_symphony.ExperimentEpochChannel * ...
                aka.MultiPulseParams & ...
                'channel_name LIKE "Amp_"' & ...
                proj(q_MP);
            data(z).current_injections.epoch_traces = fetch(epochs,'*');
            data(z).light_responses_spikes = fetch(q_SMS,'*');
            data_for_cell = data(z);
            save(sprintf('Cell_%d',ids(i)), 'data_for_cell');
            exportStructToHDF5(data_for_cell,sprintf('Cell_%d.h5',ids(i)),'/');
            z=z+1;
        end
    end
end

%% now for ACs
%% fetch SMS CC data
SMS_CC_data = sln_results.DatasetSMSCC * ...
    aka.Dataset * ...
    proj(sln_animal.Animal,'source_id->animal_source','*') * ...
    sln_animal.GenotypeString * sln_cell.Cell * ...
    sln_symphony.UserParamCellLabeled * ...
    sln_symphony.UserParamDatasetDrugPresent * ...
    proj(sln_cell.AssignType.current,'entry_time->cell_assign_entry','user_name->cell_assign_user','*') & ...
    (proj(aka.BlockParams('SpotsMultiSize'), 'mean_level') & 'mean_level=0' & 'stim_time_ms=1000') & ...
    'cell_class="amacrine"' & ...
    'dob IS NOT NULL' & ...
    'drug_present IS NULL';

SMS_CC_data = sln_results.DatasetSMSCC * ...
    aka.Dataset * ...
    sln_cell.Cell * ...
    proj(sln_cell.AssignType.current,'entry_time->cell_assign_entry','user_name->cell_assign_user','*') & ...
    'cell_class="amacrine"';

%filter datasets we don't want
SMS_CC_ACs = SMS_CC_data & ...
    'dataset_name NOT LIKE "%Laser%"' & ...
    'dataset_name NOT LIKE "%10k%"' & ...
    'dataset_name NOT LIKE "%meanON%"' & ...
    'dataset_name NOT LIKE "%mean035%"' & ...
    'dataset_name NOT LIKE "%mean0.2%"' & ...
    'dataset_name NOT LIKE "%mean_wContras%"' & ...
    'dataset_name NOT LIKE "%HighGlucose%"' & ...
    'dataset_name NOT LIKE "%Wash%"' & ...
    'dataset_name NOT LIKE "%functionalImaging%"' & ...
    'dataset_name NOT LIKE "%fromMean%"' & ...
    'dataset_name NOT LIKE "%darkspot%"' & ...
    'dataset_name NOT LIKE "%MFA%"' & ...
    'dataset_name NOT LIKE "%Z1_8Hz%"' & ...
    'dataset_name NOT LIKE "%NDF7%"' & ...
    'dataset_name NOT LIKE "%11Cis%"' & ...
    'strain_name!="WT_bead_injected"' & ...
    'strain_name!="NF1-KO"' & ...
    'strain_name!="Tusc5-eGFP"' & ...
    'strain_name!="TRPV4_cKO_bead_injected"';

%% get MP data
MP_data = sln_results.DatasetMultiPulsevaryCurrentFeatureExtract * ...
    aka.Dataset * ...
    proj(sln_animal.Animal,'source_id->animal_source','*') * ...
    sln_animal.GenotypeString * sln_cell.Cell * ...
    sln_symphony.UserParamCellLabeled * ...
    sln_symphony.UserParamDatasetDrugPresent * ...
    proj(sln_cell.AssignType.current,'entry_time->cell_assign_entry','user_name->cell_assign_user','*') & ...
    'cell_class="amacrine"' & ...
    'dob IS NOT NULL' & ...
    'drug_present IS NULL';

