q_ramp = sln_cell.Cell * sln_cell.CellName * sln_cell.AssignType.current ...
    * sln_symphony.Dataset & (sln_symphony.UserParamCellCcQuality ...
    & 'cc_quality = "high"') ...
    & 'dataset_name LIKE "Ramp%"'...
    & 'cell_class = "RGC"';

q = fetch(sln_cell.Cell * sln_cell.CellName * sln_cell.AssignType.current ...
    * sln_symphony.Dataset & (sln_symphony.UserParamCellCcQuality ...
    & 'cc_quality = "high"') ...
    & 'dataset_name LIKE "Ramp%"'...
    & 'cell_class = "RGC"', '*');

t_1 = struct2table(q);
t_2 = t_1(:, {'cell_unid', 'file_name', 'source_id'});
s_1 = table2struct(t_2)

writetable(struct2table(q), 'ramps')

q_ramp_final_table = fetch(...
    sln_cell.Cell * sln_cell.CellName * sln_cell.AssignType.current * ...
    sln_symphony.ExperimentEpochBlock & (sln_symphony.DatasetEpoch & q), '*');


q_multipulse = sln_cell.Cell * sln_symphony.UserParamDatasetExtraMp * sln_cell.CellName * sln_cell.AssignType.current ...
    * sln_symphony.ExperimentEpochBlock & (sln_symphony.DatasetEpoch * sln_symphony.Dataset & (sln_symphony.UserParamCellCcQuality ...
    & 'cc_quality = "high"') ...
    & 'dataset_name LIKE "MultiPulse%"'...
    & 'cell_class = "RGC"' & 'NOT extra_mp = "T"') & s_1 

q_multipulse_final_table = fetch( ...
    q_multipulse, '*');