function R = MultiPulse_varyCurrent(data_group, params)

datasets = aka.Dataset & data_group;
datasets_struct = fetch(datasets);
N_datasets = datasets.count;

R = table('Size',[N_datasets, 19], 'VariableNames', ...
    {'file_name', ...
    'dataset_name', ...
    'source_id', ...
    'inj_current', ...
    'n_epochs_per_current', ...
    'Vrest', ...
    'Vmax', ...
    'Vmin', ...
    'Vmax_rebound', ...
    'Vmin_rebound', ...
    'Vsteady', ...
    'Tmax', ...
    'Tmin', ...
    'Tmax_rebound', ...
    'Tmin_rebound', ...
    'mean_traces', ...
    'sample_rate' ...
    'pre_time_ms', ...
    'stim_time_ms' ...
    }, ...
    'VariableTypes', ...
    {'string', ...
    'string', ...
    'uint16', ...
    'cell', ...
    'cell', ...
    'double', ...
    'cell', ...
    'cell', ...
    'cell', ...
    'cell', ...
    'cell', ...
    'cell', ...
    'cell', ...
    'cell', ...
    'cell', ...
    'cell', ...
    'double', ...
    'uint16', ...
    'uint16' ...
    });

%assign UserData of table to be the table name
R.Properties.UserData = 'MultiPulse_varyCurrent';

%assign test descriptions for some of the variables 
R.Properties.VariableDescriptions = ...
    {'file name from symphony', ...
    'dataset name', ... 
    'source id used to identify the cell to which the dataset belongs', ...
    'vector of current injection amplitudes (pA)', ...
    'vector with how many trials for each injection size', ...
    'resting potential (mV)', ...
    'maximum positive deflection during current (mV)', ...
    'minimum negative deflection during current (mV)', ...
    'maximum positive deflection after current (mV)', ...
    'minimum negative deflection after current (mV)', ...
    'steady state deflection during last 50 ms of current (mV)', ...
    'time of maximum positive deflection during current (ms)', ...
    'time of minimum negative deflection during current (mV)', ...
    'time of maximum positive deflection after current (mV)', ...
    'time of minimum negative deflection after current (mV)', ...
    'waveforms of mean traces (mV)', ...
    'samples per second', ...
    'pre time (ms)', ...
    'stim time (ms)'...
    };

for d=1:N_datasets
    tic;
    fprintf('Processing %d of %d, %s:%s\n', d, N_datasets, datasets_struct(d).file_name, datasets_struct(d).dataset_name);

    epochs_in_dataset = fetch(sln_symphony.DatasetEpoch * ...
        sln_symphony.ExperimentChannel * ...
        sln_symphony.ExperimentEpochChannel * ...
        sln_symphony.ExperimentProtocolMultiPulseV1BlockParameters * ...
        sln_symphony.ExperimentProtocolMultiPulseV1EpochParameters & ...
        datasets_struct(d),'*');
    N_epochs = length(epochs_in_dataset);

    if N_epochs == 0
        error('No epochs in dataset: %s', datasets_struct(d).dataset_name);
    end

    %parameters to save for the whole dataset
    sample_rate = epochs_in_dataset(1).sample_rate;
    pre_stim_tail = struct('pre_time', epochs_in_dataset(1).pre_time, ...
        'stim_time', epochs_in_dataset(1).stim_1_time, ...
        'tail_time', epochs_in_dataset(1).tail_time);
    pre_samples = sample_rate * (pre_stim_tail.pre_time / 1E3);
    stim_samples = sample_rate * (pre_stim_tail.stim_time / 1E3);
    tail_samples = sample_rate * (pre_stim_tail.tail_time / 1E3);
    total_samples = pre_samples + stim_samples + tail_samples;
    ss_samples = 50E-3 * sample_rate;

    all_currents = round([epochs_in_dataset.pulse_1_curr]);
    currents  = sort(unique(all_currents));
    N_currents = length(currents);

    N_epochs_per_current = zeros(N_currents,1);
    Vmax = zeros(N_currents,1);
    Vmin = zeros(N_currents,1);
    Vmax_rebound = zeros(N_currents,1);
    Vmin_rebound = zeros(N_currents,1);
    Vsteady= zeros(N_currents,1);
    Tmax = zeros(N_currents,1);
    Tmin = zeros(N_currents,1);
    Tmax_rebound = zeros(N_currents,1);
    Tmin_rebound = zeros(N_currents,1);
    Vrest_vector = zeros(N_currents,1);
    mean_traces = zeros(N_currents, total_samples);

    for s=1:N_currents
        ind = find(all_currents == currents(s));
        N_epochs_per_current(s) = length(ind);
        trace = mean(reshape([epochs_in_dataset(ind).raw_data], [], length(ind)), 2)';
        mean_traces(s,:) = trace;
        Vrest_vector(s) = mean(trace(1:pre_samples));
       
        [Vmax(s), t] = max(trace(pre_samples+1:pre_samples+stim_samples) - Vrest_vector(s));
        Tmax(s) = 1E3 * t / sample_rate;
        [Vmin(s), t] = min(trace(pre_samples+1:pre_samples+stim_samples) - Vrest_vector(s));
        Tmin(s) = 1E3 * t / sample_rate;
        Vsteady(s) = mean(trace(pre_samples+stim_samples-ss_samples:pre_samples+stim_samples) - Vrest_vector(s));
        
        [Vmax_rebound(s), t] = max(trace(pre_samples+stim_samples+1:end) - Vrest_vector(s));
        Tmax_rebound(s) = 1E3 * t / sample_rate;
        [Vmin_rebound(s), t] = min(trace(pre_samples+stim_samples+1:end) - Vrest_vector(s));
        Tmin_rebound(s) = 1E3 * t / sample_rate;        
    end

    Vrest = mean(Vrest_vector);

    %set table variables
    R.file_name(d) = datasets_struct(d).file_name;
    R.dataset_name(d) = datasets_struct(d).dataset_name;
    R.source_id(d) = datasets_struct(d).source_id;
    R.inj_current(d) = {currents'};
    R.pre_time_ms(d) = pre_stim_tail.pre_time;
    R.stim_time_ms(d) = pre_stim_tail.stim_time;
    R.n_epochs_per_current(d) = {N_epochs_per_current};
    R.Vrest(d) = Vrest;
    R.Vsteady(d) = {Vsteady};
    R.Vmax(d) = {Vmax};
    R.Vmin(d) = {Vmin};
    R.Vmax_rebound(d) = {Vmax_rebound};
    R.Vmin_rebound(d) = {Vmin_rebound};
    R.Tmax(d) = {Tmax};
    R.Tmin(d) = {Tmin};
    R.Tmax_rebound(d) = {Tmax_rebound};
    R.Tmin_rebound(d) = {Tmin_rebound};
    R.mean_traces(d) = {mean_traces};
    R.sample_rate = sample_rate;

    fprintf('Elapsed time = %d seconds\n', round(toc));

end
