function access_token = refresh_gcal_connection(connection_name)
conn = fetch(secure.GcalConnection & sprintf('connection_name="%s"', connection_name), '*');
refresh_token = fetch1(secure.RefreshToken &  aggr(secure.GcalConnection, secure.RefreshToken, 'max(token_id)->token_id') & ...
    sprintf('connection_name="%s"', connection_name), ...
    'token');

access_response = webwrite(...
    'https://oauth2.googleapis.com/token',...
    'grant_type','refresh_token',...
    'client_id',conn.client_id,...
    'client_secret',conn.client_secret,...
    'refresh_token',refresh_token,...
    'redirect_uri','urn:ietf:wg:oauth:2.0:oob'...
    );

key_access.token = access_response.access_token;
key_access.connection_name = connection_name;
insert(secure.AccessToken, key_access);

access_token = key_access.token;