function build_hdf5(debug)
%debug = 1 to skip loading data
%debug > 1 for verbosity
if nargin && debug
    debug_string = '-DMATLAB_DEBUGGING';
    if debug > 1
        verbose_string = '-DVERBOSE';
    else
        verbose_string = '';
    end
else
    debug_string = '';
    verbose_string = '';
end
utils_folder = fileparts(mfilename('fullpath'));

switch computer('arch')
    case 'maci64'
        cd('mexmaci64')
        mex('-v','../loadSymphony2.cpp'...
            ,debug_string...
            ,verbose_string...
            ,'MACOSX_DEPLOYMENT_TARGET=11.6.2'...
            ,'libhdf5.a'...
            ,'libhdf5_cpp.a'...
            ,'libhdf5_hl.a'...
            ,'libhdf5_hl_cpp.a'...
            ,'libhdf5_tools.a'...
            ,'libsz.a'...
            ,'/usr/local/opt/zlib/lib/libz.a'...
            ,sprintf('-I%s%sinclude',utils_folder,filesep)...
            );
        cd('..');
        
    case 'win64'
        mex('loadSymphony2.cpp'...
            ,debug_string...
            ,verbose_string...
            ,'libhdf5.lib','libhdf5_cpp.lib','libhdf5_hl.lib','libhdf5_tools.lib','libhdf5_hl_cpp.lib','libzlib.lib','libsz.lib','libaec.lib'...
            ,sprintf('-I%s%sinclude',utils_folder,filesep)...
            ,sprintf('-L%s%smexw64',utils_folder,filesep)...
            );
    otherwise
        error('Don''t know how to build for target system!');
end