mex('loadSymphony2.cpp',...
    'libhdf5.lib','libhdf5_cpp.lib','libhdf5_hl.lib','libhdf5_tools.lib','libhdf5_hl_cpp.lib','libzlib.lib'...
    ,'-IC:\\Users\zjess\Downloads\CMake-hdf5-1.12.1\CMake-hdf5-1.12.1\build\_CPack_Packages\win64\ZIP\HDF5-1.12.1-win64\include'...    
   ...,'-DH5_BUILT_AS_DYNAMIC_LIB'...
);  

