function q = GLUT1_by_stack
all_cells = aggr(sln_animal.Animal * sln_imquant.GLUT1Stack,...
    proj(sln_imquant.GLUT1Cell),...
    'count(*)->n_cells', ...
    '*');

gfp_cells = aggr(sln_animal.Animal * sln_imquant.GLUT1Stack,...
    sln_imquant.GLUT1Cell & 'gfp="T"',...
    'count(*)->n_gfp');

rip_cells = aggr(sln_animal.Animal * sln_imquant.GLUT1Stack,...
    sln_imquant.GLUT1Cell & 'in_rip="T"',...
    'count(*)->n_in_rip');

q = proj(all_cells * gfp_cells * rip_cells,'n_gfp/n_cells->frac_gfp','n_in_rip/n_cells->frac_rip','*');
