function q = GLUT1_by_animal
q = aggr(sln_animal.Animal * sln_animal.GenotypeString & sln_imquant.GLUT1Stack,...
    proj(sln_imquant.GLUT1Stack,'age_at_exp'),...
    'count(*)->n_stacks','max(age_at_exp)->age','*');
