function q = GLUT3_by_eye
q = aggr(sln_animal.Eye * sln_animal.GenotypeString & sln_imquant.GLUT3Stack,...
    proj(sln_imquant.GLUT3Stack,'age_at_exp'),...
    'count(*)->n_stacks','max(age_at_exp)->age','*');