function conditions_table = plot_GLUT1_data_for_animal(animal_id)
        stacks = sln_imquant.GLUT1Stack * ...
        sln_animal.Animal * ...
        sln_animal.GenotypeString ...
        & sprintf('animal_id=%d',animal_id);
    conditions_table = sln_imquant.get_GLUT1_for_stacks(stacks,...
        {'light_condition_name','gfp'},...
        {'image_fname'},...
        {'drug_condition_name','genotype_string','animal_id','age_at_exp','sex'});
    sln_imquant.plot_GLUT1_vs_light_condition(conditions_table);
end