function required_fields = plot_MB_CA(R,ax)
if nargin < 1
    required_fields = {'spikes_leading_mean', 'bar_angles', 'spikes_leading_sem', ...
        'spikes_trailing_mean', 'spikes_trailing_sem',...
        'spikes_full_mean', 'spikes_full_sem', ...
        'dsi_leading', 'dsi_trailing', 'dsi'};
    return;
end

hold(ax,'on');
errorbar(ax, R.bar_angles, R.spikes_leading_mean, R.spikes_leading_sem,...
    'Color',[0 1 1],...
    'LineWidth',2);
errorbar(ax, R.bar_angles, R.spikes_trailing_mean, R.spikes_trailing_sem,...
    'Color',[0 0 0],...
    'LineWidth',2);
errorbar(ax, R.bar_angles, R.spikes_full_mean, R.spikes_full_sem,...
    'Color',[.5 .5 .5],...
    'LineWidth',1);
set(ax,'XtickMode','auto');
set(ax,'YtickMode','auto');
hold(ax,'on');
xlabel(ax, 'Bar angle (degrees)')
ylabel(ax, 'Spike count');
title(ax,sprintf('DSI: leading = %0.2f, trailing = %0.2f, full = %0.2f', R.dsi_leading, R.dsi_trailing, R.dsi));
legend(ax,{'Leading', 'Trailing', 'Full'});
hold(ax,'off');
