function required_fields = plot_MB_CC(R,ax)
if nargin < 1
    required_fields = {'peak_leading_mean', 'bar_angles', 'peak_trailing_mean', 'peak_leading_sem', ...
        'peak_trailing_sem', 'peak_full_mean', 'peak_full_sem', ...
        'dsi_leading_peak', 'dsi_trailing_peak', 'dsi_peak'};
    return;
end

parent_panel = get(ax,'Parent');
ax = polaraxes(parent_panel);
ax.FontUnits = 'points';
ax.FontSize = 12;
ax.Units = 'normalized';
ax.Position = [.1 .1 .8 .8];
hold(ax,'on');

angles = deg2rad(R.bar_angles);
angles(end+1) = angles(1);

vals = R.peak_leading_mean;
vals(end+1) = vals(1);
leading_line = polarplot(ax, angles, vals, ...
     'Color',[0 1 1],...
     'LineWidth',2);
vals = R.peak_leading_mean + R.peak_leading_sem;
vals(end+1) = vals(1);
polarplot(ax, angles, vals, ...
     'Color',[0 1 1],...
     'LineWidth',1, ...
     'LineStyle', '--');
vals = R.peak_leading_mean - R.peak_leading_sem;
vals(end+1) = vals(1);
polarplot(ax, angles, vals, ...
     'Color',[0 1 1],...
     'LineWidth',1, ...
     'LineStyle', '--');

vals = R.peak_trailing_mean;
vals(end+1) = vals(1);
trailing_line = polarplot(ax, angles, vals, ...
     'Color',[0 0 0],...
     'LineWidth',2);
vals = R.peak_trailing_mean + R.peak_trailing_sem;
vals(end+1) = vals(1);
polarplot(ax, angles, vals, ...
     'Color',[0 0 0],...
     'LineWidth',1, ...
     'LineStyle', '--');
vals = R.peak_trailing_mean - R.peak_trailing_sem;
vals(end+1) = vals(1);
polarplot(ax, angles, vals, ...
     'Color',[0 0 0],...
     'LineWidth',1, ...
     'LineStyle', '--');

title(ax,sprintf('DSI: leading = %0.2f, trailing = %0.2f, full = %0.2f', R.dsi_leading_peak, R.dsi_trailing_peak, R.dsi_peak));
lgd = legend(ax,[leading_line, trailing_line], {'Leading', 'Trailing'},...
    'Location','southwest');
title(lgd, 'Peak response (mV) for');
hold(ax,'off');
