function required_fields = plot_MB_CA(R,ax)
if nargin < 1
    required_fields = {'spikes_leading_mean', 'bar_angles', 'spikes_leading_sem', ...
        'spikes_trailing_mean', 'spikes_trailing_sem',...
        'spikes_full_mean', 'spikes_full_sem', ...
        'dsi_leading', 'dsi_trailing', 'dsi'};
    return;
end

parent_panel = get(ax,'Parent');
ax = polaraxes(parent_panel);
ax.FontUnits = 'points';
ax.FontSize = 12;
ax.Units = 'normalized';
ax.Position = [.1 .1 .8 .8];
hold(ax,'on');

angles = deg2rad(R.bar_angles);
angles(end+1) = angles(1);
% vals = R.spikes_full_mean;
% vals(end+1) = vals(1);
% polarplot(ax, angles, vals, ...
%      'Color',[.5 .5 .5],...
%      'LineWidth',2);
% vals = R.spikes_full_mean + R.spikes_full_sem;
% vals(end+1) = vals(1);
% polarplot(ax, angles, vals, ...
%      'Color',[.5 .5 .5],...
%      'LineWidth',1, ...
%      'LineStyle', '--');
% vals = R.spikes_full_mean - R.spikes_full_sem;
% vals(end+1) = vals(1);
% polarplot(ax, angles, vals, ...
%      'Color',[.5 .5 .5],...
%      'LineWidth',1, ...
%      'LineStyle', '--');

vals = R.spikes_leading_mean;
vals(end+1) = vals(1);
leading_line = polarplot(ax, angles, vals, ...
     'Color',[0 1 1],...
     'Marker','o',...
     'MarkerFaceColor',[0 1 1],...
     'LineWidth',2);
vals = R.spikes_leading_mean + R.spikes_leading_sem;
vals(end+1) = vals(1);
polarplot(ax, angles, vals, ...
     'Color',[0 1 1],...
     'LineWidth',1, ...
     'LineStyle', '--');
vals = R.spikes_leading_mean - R.spikes_leading_sem;
vals(end+1) = vals(1);
polarplot(ax, angles, vals, ...
     'Color',[0 1 1],...
     'LineWidth',1, ...
     'LineStyle', '--');

vals = R.spikes_trailing_mean;
vals(end+1) = vals(1);
trailing_line = polarplot(ax, angles, vals, ...
     'Color',[0 0 0],...
     'Marker','o',...
     'MarkerFaceColor',[0 0 0],...
     'LineWidth',2);
vals = R.spikes_trailing_mean + R.spikes_trailing_sem;
vals(end+1) = vals(1);
polarplot(ax, angles, vals, ...
     'Color',[0 0 0],...
     'LineWidth',1, ...
     'LineStyle', '--');
vals = R.spikes_trailing_mean - R.spikes_trailing_sem;
vals(end+1) = vals(1);
polarplot(ax, angles, vals, ...
     'Color',[0 0 0],...
     'LineWidth',1, ...
     'LineStyle', '--');


% errorbar(ax, R.bar_angles, R.spikes_leading_mean, R.spikes_leading_sem,...
%     'Color',[0 1 1],...
%     'LineWidth',2);
% errorbar(ax, R.bar_angles, R.spikes_trailing_mean, R.spikes_trailing_sem,...
%     'Color',[0 0 0],...
%     'LineWidth',2);
% errorbar(ax, R.bar_angles, R.spikes_full_mean, R.spikes_full_sem,...
%     'Color',[.5 .5 .5],...
%     'LineWidth',1);
% set(ax,'XtickMode','auto');
% set(ax,'YtickMode','auto');
% hold(ax,'on');
% xlabel(ax, 'Bar angle (degrees)')
% ylabel(ax, 'Spike count');

title(ax,sprintf('DSI: leading = %0.2f, trailing = %0.2f, full = %0.2f', R.dsi_leading, R.dsi_trailing, R.dsi));
lgd = legend(ax,[leading_line, trailing_line], {'Leading', 'Trailing'},...
    'Location','southwest');
title(lgd, 'Spike count for');
hold(ax,'off');
